-- Complete SQLite Migration: Create pension_data table with indexes
-- Date: 2025-08-18

CREATE TABLE IF NOT EXISTS pension_data (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT UNIQUE NOT NULL,
  age INTEGER,
  gender TEXT,
  country TEXT,
  employment_status TEXT,
  marital_status TEXT,
  number_of_dependents INTEGER,
  education_level TEXT,
  health_status TEXT,
  life_expectancy_estimate INTEGER,
  annual_income INTEGER,
  current_savings INTEGER,
  debt_level INTEGER,
  monthly_expenses INTEGER,
  savings_rate REAL,
  home_ownership_status TEXT,
  retirement_age_goal INTEGER,
  risk_tolerance TEXT,
  contribution_amount INTEGER,
  contribution_frequency TEXT,
  employer_contribution INTEGER,
  total_annual_contribution INTEGER,
  years_contributed INTEGER,
  investment_type TEXT,
  fund_name TEXT,
  annual_return_rate REAL,
  volatility REAL,
  fees_percentage REAL,
  investment_experience_level TEXT,
  portfolio_diversity_score REAL,
  projected_pension_amount INTEGER,
  expected_annual_payout INTEGER,
  inflation_adjusted_payout INTEGER,
  years_of_payout INTEGER,
  survivor_benefits TEXT,
  pension_type TEXT,
  withdrawal_strategy TEXT,
  tax_benefits_eligibility TEXT,
  government_pension_eligibility TEXT,
  private_pension_eligibility TEXT,
  insurance_coverage TEXT,
  financial_goals TEXT,
  transaction_id TEXT,
  transaction_amount INTEGER,
  transaction_date TEXT,
  transaction_channel TEXT,
  time_of_transaction REAL,
  suspicious_flag TEXT,
  anomaly_score REAL,
  transaction_pattern_score REAL,
  previous_fraud_flag TEXT,
  ip_address TEXT,
  device_id TEXT,
  geo_location TEXT,
  account_age INTEGER,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
)
